main: uk.co.hollowworld.plugins.hollowrpg.HollowRPG
name: HollowRPG
version: 1.2
author: Chris Herbert
description: Hollowworld Roleplaying Plugin.
commands:
    my:
        description: A test command.
        usage: /<command>
depend: [Citizens]
softdepend: [Citizens]